theme: jekyll-theme-minimal
title: [Colton Grainger]
description: [episcopal service corps member. clerk in refugee medical care. aspiring mathematician.]
show_downloads: [true]
google_analytics: [UA-99597867-1]
