theme: jekyll-theme-primer
title: [blog.quamash.net]
description: [Colton Grainger's blog]
highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

    scope:
      path: "_posts"
    values:
      permalink: /:title:output_ext
