theme: jekyll-theme-primer
title: [Colton's weblog]
description: []
highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

    scope:
      path: "_posts"
    values:
      permalink: /:title:output_ext
