theme: jekyll-theme-primer
title: [Colton Grainger]
description: [Olympia&#44; WA]
google_analytics: [UA-99597867-1]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

    scope:
      path: "_posts"
    values:
      permalink: /:title:output_ext
